# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-01 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wow', '0002_post_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.TextField(choices=[(1, 'public'), (2, 'privete')], default=1),
        ),
    ]
