# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-02 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wow', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[(1, b'public'), (2, b'private')], default=1, max_length=200),
        ),
    ]
