# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-02 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wow', '0005_auto_20190402_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='public', max_length=200),
        ),
    ]
